# SITE CONFIGURATION
baseurl:            ""
url:                "http://kellyc.eu"
reading_time:       true
words_per_minute:   200
email:              kelly.crabbe@gmail.com

# THEME-SPECIFIC CONFIGURATION
title:              Kelly C.
description:        "My own little nook on the interwebz where I discuss a multitude of topics in my own life."
avatar:             assets/img/triangle.png
favicon:            assets/favicon.ico

# Header and footer text
header_text: "Life as it is"
header_feature_image: assets/img/lens-header.jpg
footer_text: >
  Powered by <a href="https://jekyllrb.com/">Jekyll</a> with <a href="https://github.com/sylhare/Type-on-Strap">Type on Strap</a> as base.

# Blog
excerpt: truncate
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
katex: false                                            # Math Markup
google_analytics: UA-150465502-1                        # Google Analytics
disqus_shortname: moonwitch                             # Disqus
layout_variables:                                       # Open the "_sass > base" folder, and open "_variables.scss"
footer_icons:                                           # In _data/social.yml
share_buttons:                                          # In _data/social.yml
authors:                                                # In _data/authors.yml
language:                                               # In _data/language.yml

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
markdown: kramdown
kramdown:
  auto_ids:           true
  footnote_nr:        1
  entity_output:      as_char
  toc_levels:         1..6
  enable_coderay:     false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    default_lang: bash
    span:
      line_numbers: false
    block:
      line_numbers: true
mathjax:              true
highlighter:          rouge
sass:
  sass_dir:           _sass
  style:              :compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", "Gemfile", "Gemfile.lock", "type-on-strap.gemspec", "*.gem", ".idea", "vendor/*",
          "LICENSE", "README.md", "screenshot.png", "assets/package.json", "assets/node_modules", "assets/gulpfile.js"]

# PROSE SETTINGS
prose:
  rooturl: '_posts'
  siteurl: "https://kellyc.eu"
  media: /assets/img/posts
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "false"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by comma's"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured?"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Comments"
          value: false
      - name: "category"
        field:
          element: "select"
          label: "Select Category"
          placeholder: "Choose Category"
          options:
            - name: "Gallery"
              value: "gallery"
            - name: "Blog"
              value: "blog"
            - name: "Portfolio"
              value: "portfolio"
            - name: "QuickTips"
              value: "quicktips"
            - name: "Reviews"
              value: "reviews"
