name: Kelly Crabbé
description: Some random description should be given.
url: http://kellyc.eu
baseurl: '' # does not include hostname

# Location of things
source:       .
destination:  ./_site
layouts_dir:      ./_layouts
data_dir:  ./_data

# Handling of
include:      ['.htaccess']
keep_files:   ['.git','.svn']
exclude:      ['mainsite.*','CNAME','Rakefile','Gemfile*']
markdown_ext: 'markdown,mkd,md'
encoding:     'utf-8'

# Conversions
markdown:     kramdown
highlighter:  rouge
excerpt_separator: "\n\n"

# Filtering Content
future:       true
show_drafts:  nil
limit_posts:  0

# Output
permalink: pretty

# GH Plugins
plugins:
- jemoji
- jekyll-sitemap
- jekyll-feed
- jekyll-gist
- jekyll-github-metadata

# Markdown Processors
kramdown:
  input: GFM

# CSS Preprocessors
sass:
  sass_dir: public/css
  style: nested
