# Welcome to Jekyll!
lang: en-US
title:              Kelly C.
tagline:            Where everything comes together...
email:              kelly.crabbe@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My own little nook on the interwebz where I discuss a multitude of topics in my own life.
baseurl: "" # the subpath of your site, e.g. /blog
url:                "http://kellyc.eu"

author:
  name:
  twitter:
  picture:
twitter_username:
github_username:
logo: # path of site logo, e.g. "/assets/images/logo.png"
search: # true, false (default)
search_full_content: false # true, false (default)
search_provider: # lunr (default), algolia
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false

# Build settings
markdown: kramdown
theme: jekyll-theme-basically-basic
plugins: # previsously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Exclude from processing.
exclude:
  - .asset-cache
  - .bundle
  - .codeclimate.yml
  - .editorconfig
  - .gitattributes
  - .jekyll-assets-cache
  - .sass-cache
  - .scss-lint.yml
  - CHANGELOG
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules
  - Rakefile
  - README
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - /docs # ignore Basically Basic sample site
  - /example # ignore Basically Basic dev site

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true

# Set Prose.io Config
prose:
  rooturl: '_posts'
  siteurl: 'http://kellyc.eu'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  _posts:
    - name: "layout"
      field:
        element: "multiselect"
        label: "Choose Layout"
        value: "post"
        options:
          - name: "default"
            value: "default"
          - name: "page"
            value: "page"
          - name: "blog post"
            value: "post"
    - name: "category"
      field:
        element: "hidden"
        value: "blog"
    - name: "tags"
      field:
        element: "multiselect"
        label: "Add tags"
        placeholder: "Add tags"
        alterable: true
    - name: "title"
      field:
        element: "text"
        label: "Post title"
        placeholder: "Title"
        alterable: true
    - name: "image"
      field:
        element: "text"
        label: "Add Image to Post"
        placeholder: "Image path (relative to /assets/post-images/)"
        alterable: true

# Set Excerpt Seperator
excerpt_separator: <!--more-->
