######################## default configuration ####################
baseURL: /
title: Kelly and Coffee
languageCode: en-US
defaultContentLanguage: en
enableEmoji: true
summaryLength: 10
paginate: 6
enableGitInfo: true # Change 'Lastmod' to latest git commit
removePathAccents: true # Because I may type accents

# theme: hugo-theme-loumans

#################### Navigation ####################
# sectionPagesMenu: "main"
menu:
  main:
    - name: Posts
      url: /posts
      weight: 1
    - name: About
      url: /about
      weight: 2
    - name: Tags
      url: /tags
      weight: 4
    - name: Resume
      url: /resume
      weight: 5

#################### Taxonomies;grouping ####################
# Must include default tags and categories
taxonomies:
  category: categories
  tag: tags

#################### default parameters ################################
params:
  paginate: 6
  logo: images/header2.png
  home: Home
  description: A personal blog in both English and Dutch.
  author: Kelly Crabbé
  avatar: true
  bio: >-
    I am a geeky happily married woman, who works as a junior DevOps after having a 15yr affaire with System Administration. I am the proud mom of a 2 yo English Cocker Spaniel and a wonderfull 21 yo plusdaughter; together with my wife we occupy a small space in this crazy world.
  googleAnalitycs: G-WYTPMHCV3B
  mobile: +32479695560
  email: kelly.crabbe@gmail.com
  location: "Neerlinter,België"
  copyright: >-
    | copyright &copy; 2022 [Kelly Crabbé](https://kellyand.coffee)
    All Rights Reserved |
  preloader:
    enable: true
    preloader: ""
  search:
    enable: true
  social:
    - title: facebook
      link: "https://facebook.com/kaymoonwitch"
    - title: twitter
      link: "https://twitter.com/kaymoonwitch"
    - title: instagram
      link: "https://https://instagram.com/kaymoonwitch"
    - title: github
      link: "https://github.com/moonwitch"
    - title: linkedin
      link: "https://www.linkedin.com/in/kellycrabbe"
    - title: 500px
      link: https://500px.com/p/kellycrabbe
    - title: deviantart
      link: https://www.deviantart.com/kay-moonwitch
  comments:
    provider: giscus
    commentable:
      page: true
      post: true
      docs: false
      project: false
      publication: true
      talk: false
    giscus:
      repo: moonwitch/moonwitch.github.io
      repo_id: R_kgDOGiHVbw
      category: Announcements
      category_id: DIC_kwDOGiHVb84CAgCM
      mapping: pathname
      input_position: top
      metadata_enabled: 0
      reactions_enabled: 1
      label: comment
      theme: light
