baseURL: /
languageCode: nl-be
title: Kelly and Coffee
author: Kelly Crabbé

# Theme Settings
theme: Loumans

# Menu settings
# sectionPagesMenu: "main"
menu:
  main:
  - name: "Home"
    pre: "home"
    url: "/"
    weight: 1
  - name: "Articles"
    pre: "pen-tool"
    url: "/articles/"
    weight: 2
  - name: "Recipes"
    pre: 'book-open'
    url: '/recipes/'
    weight: 3
  - name: "Tags"
    pre: "tag" 
    url: "/tags/"
    weight: 4

taxonomies:
  tag: 'Tags'
