baseURL: ''
title: Kelly and Coffee
author: Kelly Crabbé
languageCode: en
theme: hugo-theme-basic
copyright: Copyright © 2021 - Kelly Crabbé
paginate: 3
enableEmoji: true 

MetaDataFormat: yaml
enableInlineShortcodes: true
footnoteReturnLinkContents: ^

# Theme i18n support
DefaultContentLanguage: en

ignoreErrors: 
  - error-missing-instagram-accesstoken

# Theme Params
params:
  titleEmoji: ":tada:"
  logo:
    logoImage: /images/kelly-and-coffee.png
  mainSections:
    - post
    - article
  description: All things that occupy my head.
  menu:
    - name: blog
      url: post/
    - name: post series
      url: series/
    - name: about
      url: about/
      
Permalinks:
  post: 'post/:slug'


taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: true
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true
