baseURL: /
languageCode: nl-be
defaultContentLanguage: nl
title: Kelly and Coffee
subtitle: Want Kelly en koffie zijn nagenoeg één geheel.

enableEmoji: true
copyright: Kelly Crabbé
#googleAnalytics: ID

# Change 'Lastmod' to latest git commit
enableGitInfo: true

# Because I may type accents
removePathAccents: true

# Menu
sectionPagesMenu: "main"

# Theme
theme: loumans

# Taxonomies;grouping
# Must include default tags and categories
taxonomies:
  category: categories
  tag: tags
  mood: moods

sitemap:
  changefreq: "monthly"
  filename: "sitemap.xml"
  priority: 0.5

permalinks:
  blog: "/:title/"

# Comments
comments:
  provider: giscus
  commentable:
    page: true
    post: true
    docs: false
    project: false
    publication: true
    talk: false
  giscus:
    repo: moonwitch/the-coffee-site
    repo_id: R_kgDOGiHVbw
    category: Announcements
    category_id: DIC_kwDOGiHVb84CAgCM
    mapping: pathname
    reactions_enabled: 1
    label: comment
    theme: light