name = "Hugo-Loumans"
license = "MIT"
licenselink = "https://github.com/moonwitch/hugo-loumans/blob/master/LICENSE.md"
description = "Loumans is a modern, simple and beautiful Hugo theme"
author = "Kelly Crabbé"
homepage = "https://github.com/moonwitch/Hugo-Loumans/tree/release"
source_repo = "git@github.com:moonwitch/Hugo-Loumans.git"
tags = ["Responsive", "Blog", "Google analytics", "Giscus", "Clean", "Tags", "Minimal", "Minimalist", "Simple", "White", "Starter"]
features = ["blog"]
min_version = 0.01
